server:
  port: 8083
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://bd:5432/lottery-db
    username: jaine
    password: 123456
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-sql: true